In [1]:
import torch
from torch import nn
import torch.nn.functional as F

In [2]:
batch_size = 8
T = 6
d_model = 4
d = 2

W = torch.normal(mean=0, std=0.01, size=(d_model, d))

x = torch.normal(mean=0, std=0.01, size=(batch_size, T, d_model))

In [30]:
def batched_matmul(x_batched, W):
    # # Assuming x_batched.shape == (batch_size, T, d_model)
    # # and W.shape == (d_model, d)
    # batch_size, T, d_model = x_batched.shape
    # d = W.shape[1]

    # # Reshape x_batched to (batch_size * T, d_model)
    # x_reshaped = x_batched.reshape(-1, d_model)

    # # Perform matrix multiplication
    # result = torch.matmul(x_reshaped, W)

    # # Reshape the result back to (batch_size, T, d)
    # result = result.reshape(batch_size, T, d)

    # return result
    
    
    batch_size = x_batched.shape[0]
    W_repeated = W.unsqueeze(0).repeat((batch_size, 1, 1))
    # print(W.shape)
    # print(W_repeated.shape)
    # print(W)
    # print(W_repeated[2])
    
    print(x_batched[0])
    print(W_repeated[0])
    
    return torch.bmm(x_batched, W_repeated)

batched_matmul(torch.ones(8, 4, 3).float(), torch.arange(12).reshape((3, 4)).float())

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])
tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.]])


tensor([[[12., 15., 18., 21.],
         [12., 15., 18., 21.],
         [12., 15., 18., 21.],
         [12., 15., 18., 21.]],

        [[12., 15., 18., 21.],
         [12., 15., 18., 21.],
         [12., 15., 18., 21.],
         [12., 15., 18., 21.]],

        [[12., 15., 18., 21.],
         [12., 15., 18., 21.],
         [12., 15., 18., 21.],
         [12., 15., 18., 21.]],

        [[12., 15., 18., 21.],
         [12., 15., 18., 21.],
         [12., 15., 18., 21.],
         [12., 15., 18., 21.]],

        [[12., 15., 18., 21.],
         [12., 15., 18., 21.],
         [12., 15., 18., 21.],
         [12., 15., 18., 21.]],

        [[12., 15., 18., 21.],
         [12., 15., 18., 21.],
         [12., 15., 18., 21.],
         [12., 15., 18., 21.]],

        [[12., 15., 18., 21.],
         [12., 15., 18., 21.],
         [12., 15., 18., 21.],
         [12., 15., 18., 21.]],

        [[12., 15., 18., 21.],
         [12., 15., 18., 21.],
         [12., 15., 18., 21.],
         [12., 15., 18., 

In [13]:
# x * W_K
# x.shape -->                   (batch_size, T, d_model)
# W.shape -->                   (d_model, d_K)

# Objective.shape -->           (batch_size, T, d)
assert batched_matmul(x, W).shape == (batch_size, T, d)
print("Correct")

torch.Size([4, 2])
torch.Size([8, 4, 2])


AssertionError: 

In [ ]:
a = torch.tensor([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])
a

In [ ]:
b = torch.tensor([[7, 8], [9, 10]])
b

In [ ]:
batched_matmul(a, b)